name: eggnstone_charts
description: A Flutter package
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.6.0

executables:
  eggnstone_charts: eggnstone_charts

dependencies:
  flutter:
    sdk: flutter
  eggnstone_dart: ^1.4.1
  freezed_annotation: ^3.0.0
  kt_dart: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  test: any

dependency_overrides:
  #

flutter:
  uses-material-design: true
