name: widgetbook_workspace
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  eggnstone_charts:
    path: ../
  intl: ^0.20.2
  widgetbook: ^3.14.1
  widgetbook_annotation: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  widgetbook_generator: ^3.13.0

flutter:
  uses-material-design: true
